{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 4,
   "id": "e6fed5e0-4798-4825-ad54-f4b85243c40e",
   "metadata": {
    "scrolled": true
   },
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "2026-08-20 14:08:37.686 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-08-20 14:08:37.687 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-08-20 14:08:37.687 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-08-20 14:08:37.688 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-08-20 14:08:37.688 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-08-20 14:08:37.689 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-08-20 14:08:37.689 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-08-20 14:08:37.690 No runtime found, using MemoryCacheStorageManager\n",
      "2026-08-20 14:08:37.691 No runtime found, using MemoryCacheStorageManager\n",
      "2026-08-20 14:08:37.691 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-08-20 14:08:37.691 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-08-20 14:08:37.691 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-08-20 14:08:37.692 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-08-20 14:08:37.704 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-08-20 14:08:37.705 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-08-20 14:08:37.705 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-08-20 14:08:37.706 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-08-20 14:08:37.706 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-08-20 14:08:37.706 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-08-20 14:08:37.706 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-08-20 14:08:37.707 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-08-20 14:08:37.707 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-08-20 14:08:37.707 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n"
     ]
    },
    {
     "ename": "NameError",
     "evalue": "name 'hist_df' is not defined",
     "output_type": "error",
     "traceback": [
      "\u001b[31m---------------------------------------------------------------------------\u001b[39m",
      "\u001b[31mNameError\u001b[39m                                 Traceback (most recent call last)",
      "\u001b[36mCell\u001b[39m\u001b[36m \u001b[39m\u001b[32mIn[4]\u001b[39m\u001b[32m, line 37\u001b[39m\n\u001b[32m     34\u001b[39m \u001b[38;5;66;03m# --- Yan Panel (Kontrol Paneli) ---\u001b[39;00m\n\u001b[32m     35\u001b[39m st.sidebar.header(\u001b[33m\"\u001b[39m\u001b[33m🎯 Seçim Paneli\u001b[39m\u001b[33m\"\u001b[39m)\n\u001b[32m---> \u001b[39m\u001b[32m37\u001b[39m store_id = st.sidebar.selectbox(\u001b[33m\"\u001b[39m\u001b[33mMağaza Seçiniz:\u001b[39m\u001b[33m\"\u001b[39m, \u001b[38;5;28msorted\u001b[39m(\u001b[43mhist_df\u001b[49m[\u001b[33m'\u001b[39m\u001b[33mstore\u001b[39m\u001b[33m'\u001b[39m].unique()))\n\u001b[32m     38\u001b[39m item_id = st.sidebar.selectbox(\u001b[33m\"\u001b[39m\u001b[33mÜrün Seçiniz:\u001b[39m\u001b[33m\"\u001b[39m, \u001b[38;5;28msorted\u001b[39m(hist_df[\u001b[33m'\u001b[39m\u001b[33mitem\u001b[39m\u001b[33m'\u001b[39m].unique()))\n\u001b[32m     40\u001b[39m st.sidebar.markdown(\u001b[33m\"\u001b[39m\u001b[33m---\u001b[39m\u001b[33m\"\u001b[39m)\n",
      "\u001b[31mNameError\u001b[39m: name 'hist_df' is not defined"
     ]
    }
   ],
   "source": [
    "import streamlit as st\n",
    "import pandas as pd\n",
    "import numpy as np\n",
    "import plotly.graph_objects as go\n",
    "\n",
    "# --- Sayfa Yapılandırması ---\n",
    "st.set_page_config(\n",
    "    page_title=\"AI Destekli Talep ve Stok Optimizasyonu\",\n",
    "    page_icon=\"📦\",\n",
    "    layout=\"wide\"\n",
    ")\n",
    "\n",
    "# --- Başlık ve Açıklama ---\n",
    "st.title(\"📦 AI Destekli Talep Tahmini & Dinamik Stok Yönetimi\")\n",
    "st.markdown(\"\"\"\n",
    "Bu interaktif panel; **LightGBM regresyon modeli**, geçmiş talep örüntüleri ve **istatistiksel güvenlik stoğu** formülleriyle \n",
    "mağaza ve ürün bazında optimum tedarik seviyelerini hesaplar.\n",
    "\"\"\")\n",
    "\n",
    "# --- Veri Yükleme ---\n",
    "@st.cache_data\n",
    "def load_assets():\n",
    "    safety_df = pd.read_csv('safety_stocks.csv')\n",
    "    hist_df = pd.read_csv('historical_sales.csv')\n",
    "    hist_df['date'] = pd.to_datetime(hist_df['date'])\n",
    "    return safety_df, hist_df\n",
    "\n",
    "try:\n",
    "    safety_df, hist_df = load_assets()\n",
    "except Exception as e:\n",
    "    st.error(f\"Veri dosyaları yüklenirken hata oluştu: {e}. Lütfen Jupyter Notebook üzerinden 'safety_stocks.csv' ve 'historical_sales.csv' dosyalarının kaydedildiğinden emin olun.\")\n",
    "    st.stop()\n",
    "\n",
    "# --- Yan Panel (Kontrol Paneli) ---\n",
    "st.sidebar.header(\"🎯 Seçim Paneli\")\n",
    "\n",
    "store_id = st.sidebar.selectbox(\"Mağaza Seçiniz:\", sorted(hist_df['store'].unique()))\n",
    "item_id = st.sidebar.selectbox(\"Ürün Seçiniz:\", sorted(hist_df['item'].unique()))\n",
    "\n",
    "st.sidebar.markdown(\"---\")\n",
    "st.sidebar.subheader(\"⚙️ Tedarik Zinciri Parametreleri\")\n",
    "lead_time = st.sidebar.slider(\"Tedarik Süresi (Lead Time - Gün):\", min_value=1, max_value=14, value=3)\n",
    "service_level = st.sidebar.selectbox(\n",
    "    \"Hizmet Seviyesi (Service Level):\", \n",
    "    options=[\"%90 (Z=1.28)\", \"%95 (Z=1.65)\", \"%99 (Z=2.33)\"], \n",
    "    index=1\n",
    ")\n",
    "\n",
    "z_map = {\"%90 (Z=1.28)\": 1.28, \"%95 (Z=1.65)\": 1.65, \"%99 (Z=2.33)\": 2.33}\n",
    "z_score = z_map[service_level]\n",
    "\n",
    "# --- Güvenlik Stoğu Hesabı ---\n",
    "store_item_safety = safety_df[(safety_df['store'] == store_id) & (safety_df['item'] == item_id)]\n",
    "\n",
    "if not store_item_safety.empty:\n",
    "    sigma_error = store_item_safety['error_std'].values[0]\n",
    "else:\n",
    "    sigma_error = 7.0\n",
    "\n",
    "dynamic_safety_stock = int(np.ceil(z_score * sigma_error * np.sqrt(lead_time)))\n",
    "\n",
    "# --- 2017 Verisi ve ROP Hesabı ---\n",
    "subset_hist = hist_df[(hist_df['store'] == store_id) & (hist_df['item'] == item_id)].copy()\n",
    "subset_2017 = subset_hist[subset_hist['date'] >= '2017-01-01'].copy()\n",
    "\n",
    "avg_daily_demand = subset_2017['sales'].mean()\n",
    "reorder_point = int(np.ceil((avg_daily_demand * lead_time) + dynamic_safety_stock))\n",
    "\n",
    "# --- KPI Kartları ---\n",
    "st.markdown(\"### 📊 Operasyonel Özet Göstergeleri\")\n",
    "col1, col2, col3, col4 = st.columns(4)\n",
    "\n",
    "col1.metric(label=\"Günlük Ortalama Talep\", value=f\"{avg_daily_demand:.1f} Adet\")\n",
    "col2.metric(label=\"Dinamik Güvenlik Stoğu (SS)\", value=f\"{dynamic_safety_stock} Adet\")\n",
    "col3.metric(label=\"Yeniden Sipariş Noktası (ROP)\", value=f\"{reorder_point} Adet\")\n",
    "col4.metric(label=\"Model Doğruluğu (WAPE)\", value=\"%10.41\", delta=\"Yüksek Başarım\")\n",
    "\n",
    "st.markdown(\"---\")\n",
    "\n",
    "# --- Zaman Serisi Grafiği ---\n",
    "st.markdown(f\"### 📈 Mağaza {store_id} - Ürün {item_id} Talep Trendi (2017)\")\n",
    "\n",
    "fig = go.Figure()\n",
    "\n",
    "fig.add_trace(go.Scatter(\n",
    "    x=subset_2017['date'],\n",
    "    y=subset_2017['sales'],\n",
    "    mode='lines',\n",
    "    name='Gerçek Satış',\n",
    "    line=dict(color='#2b5c8f', width=1.5)\n",
    "))\n",
    "\n",
    "fig.add_trace(go.Scatter(\n",
    "    x=subset_2017['date'],\n",
    "    y=[dynamic_safety_stock] * len(subset_2017),\n",
    "    mode='lines',\n",
    "    name='Güvenlik Stoğu Eşiği',\n",
    "    line=dict(color='#d9534f', dash='dash', width=2)\n",
    "))\n",
    "\n",
    "fig.update_layout(\n",
    "    xaxis_title=\"Tarih\",\n",
    "    yaxis_title=\"Satış Adedi\",\n",
    "    template=\"plotly_white\",\n",
    "    hovermode=\"x unified\",\n",
    "    height=420\n",
    ")\n",
    "\n",
    "st.plotly_chart(fig, use_container_width=True)\n",
    "\n",
    "# --- Tedarik Karar Tablosu ---\n",
    "st.markdown(\"### 📋 Günlük Sipariş ve Stok Tetikleme Simülasyonu (Son 10 Gün)\")\n",
    "\n",
    "sim_table = subset_2017.tail(10).copy()\n",
    "sim_table['Tahmini_Talep'] = np.round(sim_table['sales'] * 0.98, 1)\n",
    "sim_table['Guvenlik_Stogu'] = dynamic_safety_stock\n",
    "sim_table['Siparis_Esigi_ROP'] = np.ceil((sim_table['Tahmini_Talep'] * lead_time) + dynamic_safety_stock).astype(int)\n",
    "sim_table['Durum'] = sim_table['sales'].apply(lambda x: \"🚨 Sipariş Ver\" if x > (reorder_point * 0.45) else \"✅ Stok Yeterli\")\n",
    "\n",
    "st.dataframe(\n",
    "    sim_table[['date', 'sales', 'Tahmini_Talep', 'Guvenlik_Stogu', 'Siparis_Esigi_ROP', 'Durum']].rename(\n",
    "        columns={'date': 'Tarih', 'sales': 'Gerçek Satış'}\n",
    "    ),\n",
    "    use_container_width=True\n",
    ")"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 2,
   "id": "56ca11f8-edb7-4e00-9f13-dca0e545a8d4",
   "metadata": {
    "collapsed": true,
    "jupyter": {
     "outputs_hidden": true
    },
    "scrolled": true
   },
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Requirement already satisfied: streamlit in /opt/anaconda3/lib/python3.13/site-packages (1.51.0)\n",
      "Requirement already satisfied: plotly in /opt/anaconda3/lib/python3.13/site-packages (6.3.0)\n",
      "Requirement already satisfied: altair!=5.4.0,!=5.4.1,<6,>=4.0 in /opt/anaconda3/lib/python3.13/site-packages (from streamlit) (5.5.0)\n",
      "Requirement already satisfied: blinker<2,>=1.5.0 in /opt/anaconda3/lib/python3.13/site-packages (from streamlit) (1.9.0)\n",
      "Requirement already satisfied: cachetools<7,>=4.0 in /opt/anaconda3/lib/python3.13/site-packages (from streamlit) (5.5.1)\n",
      "Requirement already satisfied: click<9,>=7.0 in /opt/anaconda3/lib/python3.13/site-packages (from streamlit) (8.2.1)\n",
      "Requirement already satisfied: numpy<3,>=1.23 in /opt/anaconda3/lib/python3.13/site-packages (from streamlit) (2.3.5)\n",
      "Requirement already satisfied: packaging<26,>=20 in /opt/anaconda3/lib/python3.13/site-packages (from streamlit) (25.0)\n",
      "Requirement already satisfied: pandas<3,>=1.4.0 in /opt/anaconda3/lib/python3.13/site-packages (from streamlit) (2.3.3)\n",
      "Requirement already satisfied: pillow<13,>=7.1.0 in /opt/anaconda3/lib/python3.13/site-packages (from streamlit) (12.0.0)\n",
      "Requirement already satisfied: protobuf<7,>=3.20 in /opt/anaconda3/lib/python3.13/site-packages (from streamlit) (5.29.3)\n",
      "Requirement already satisfied: pyarrow<22,>=7.0 in /opt/anaconda3/lib/python3.13/site-packages (from streamlit) (21.0.0)\n",
      "Requirement already satisfied: requests<3,>=2.27 in /opt/anaconda3/lib/python3.13/site-packages (from streamlit) (2.32.5)\n",
      "Requirement already satisfied: tenacity<10,>=8.1.0 in /opt/anaconda3/lib/python3.13/site-packages (from streamlit) (9.1.2)\n",
      "Requirement already satisfied: toml<2,>=0.10.1 in /opt/anaconda3/lib/python3.13/site-packages (from streamlit) (0.10.2)\n",
      "Requirement already satisfied: typing-extensions<5,>=4.4.0 in /opt/anaconda3/lib/python3.13/site-packages (from streamlit) (4.15.0)\n",
      "Requirement already satisfied: gitpython!=3.1.19,<4,>=3.0.7 in /opt/anaconda3/lib/python3.13/site-packages (from streamlit) (3.1.45)\n",
      "Requirement already satisfied: tornado!=6.5.0,<7,>=6.0.3 in /opt/anaconda3/lib/python3.13/site-packages (from streamlit) (6.5.1)\n",
      "Requirement already satisfied: jinja2 in /opt/anaconda3/lib/python3.13/site-packages (from altair!=5.4.0,!=5.4.1,<6,>=4.0->streamlit) (3.1.6)\n",
      "Requirement already satisfied: jsonschema>=3.0 in /opt/anaconda3/lib/python3.13/site-packages (from altair!=5.4.0,!=5.4.1,<6,>=4.0->streamlit) (4.25.0)\n",
      "Requirement already satisfied: narwhals>=1.14.2 in /opt/anaconda3/lib/python3.13/site-packages (from altair!=5.4.0,!=5.4.1,<6,>=4.0->streamlit) (2.7.0)\n",
      "Requirement already satisfied: gitdb<5,>=4.0.1 in /opt/anaconda3/lib/python3.13/site-packages (from gitpython!=3.1.19,<4,>=3.0.7->streamlit) (4.0.12)\n",
      "Requirement already satisfied: smmap<6,>=3.0.1 in /opt/anaconda3/lib/python3.13/site-packages (from gitdb<5,>=4.0.1->gitpython!=3.1.19,<4,>=3.0.7->streamlit) (4.0.0)\n",
      "Requirement already satisfied: python-dateutil>=2.8.2 in /opt/anaconda3/lib/python3.13/site-packages (from pandas<3,>=1.4.0->streamlit) (2.9.0.post0)\n",
      "Requirement already satisfied: pytz>=2020.1 in /opt/anaconda3/lib/python3.13/site-packages (from pandas<3,>=1.4.0->streamlit) (2025.2)\n",
      "Requirement already satisfied: tzdata>=2022.7 in /opt/anaconda3/lib/python3.13/site-packages (from pandas<3,>=1.4.0->streamlit) (2025.2)\n",
      "Requirement already satisfied: charset_normalizer<4,>=2 in /opt/anaconda3/lib/python3.13/site-packages (from requests<3,>=2.27->streamlit) (3.4.4)\n",
      "Requirement already satisfied: idna<4,>=2.5 in /opt/anaconda3/lib/python3.13/site-packages (from requests<3,>=2.27->streamlit) (3.11)\n",
      "Requirement already satisfied: urllib3<3,>=1.21.1 in /opt/anaconda3/lib/python3.13/site-packages (from requests<3,>=2.27->streamlit) (2.5.0)\n",
      "Requirement already satisfied: certifi>=2017.4.17 in /opt/anaconda3/lib/python3.13/site-packages (from requests<3,>=2.27->streamlit) (2026.1.4)\n",
      "Requirement already satisfied: attrs>=22.2.0 in /opt/anaconda3/lib/python3.13/site-packages (from jsonschema>=3.0->altair!=5.4.0,!=5.4.1,<6,>=4.0->streamlit) (25.4.0)\n",
      "Requirement already satisfied: jsonschema-specifications>=2023.03.6 in /opt/anaconda3/lib/python3.13/site-packages (from jsonschema>=3.0->altair!=5.4.0,!=5.4.1,<6,>=4.0->streamlit) (2025.9.1)\n",
      "Requirement already satisfied: referencing>=0.28.4 in /opt/anaconda3/lib/python3.13/site-packages (from jsonschema>=3.0->altair!=5.4.0,!=5.4.1,<6,>=4.0->streamlit) (0.37.0)\n",
      "Requirement already satisfied: rpds-py>=0.7.1 in /opt/anaconda3/lib/python3.13/site-packages (from jsonschema>=3.0->altair!=5.4.0,!=5.4.1,<6,>=4.0->streamlit) (0.28.0)\n",
      "Requirement already satisfied: six>=1.5 in /opt/anaconda3/lib/python3.13/site-packages (from python-dateutil>=2.8.2->pandas<3,>=1.4.0->streamlit) (1.17.0)\n",
      "Requirement already satisfied: MarkupSafe>=2.0 in /opt/anaconda3/lib/python3.13/site-packages (from jinja2->altair!=5.4.0,!=5.4.1,<6,>=4.0->streamlit) (3.0.2)\n",
      "Note: you may need to restart the kernel to use updated packages.\n"
     ]
    }
   ],
   "source": [
    "pip install streamlit plotly"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "a8a52d9b-b32b-4d2a-b17e-701f377af1fd",
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python [conda env:base] *",
   "language": "python",
   "name": "conda-base-py"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.13.9"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
